name: Pull Request Checker

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
